#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : g2fs-utils
Version  : 3.2.0
Release  : 1
URL      : https://pagure.io/gfs2-utils/archive/3.2.0/gfs2-utils-3.2.0.tar.gz
Source0  : https://pagure.io/gfs2-utils/archive/3.2.0/gfs2-utils-3.2.0.tar.gz
Summary  : No detailed summary available
Group    : Development/Tools
License  : GPL-2.0 LGPL-2.1
Requires: g2fs-utils-bin = %{version}-%{release}
Requires: g2fs-utils-config = %{version}-%{release}
Requires: g2fs-utils-license = %{version}-%{release}
Requires: g2fs-utils-man = %{version}-%{release}
BuildRequires : bison
BuildRequires : flex
BuildRequires : pkgconfig(blkid)
BuildRequires : pkgconfig(check)
BuildRequires : pkgconfig(ncurses)
BuildRequires : pkgconfig(uuid)
BuildRequires : pkgconfig(zlib)

%description
gfs2-utils
----------
This package contains the tools needed to create, check, manipulate and analyze
gfs2 filesystems, along with important scripts required to support gfs2
clusters.

%package bin
Summary: bin components for the g2fs-utils package.
Group: Binaries
Requires: g2fs-utils-config = %{version}-%{release}
Requires: g2fs-utils-license = %{version}-%{release}

%description bin
bin components for the g2fs-utils package.


%package config
Summary: config components for the g2fs-utils package.
Group: Default

%description config
config components for the g2fs-utils package.


%package doc
Summary: doc components for the g2fs-utils package.
Group: Documentation
Requires: g2fs-utils-man = %{version}-%{release}

%description doc
doc components for the g2fs-utils package.


%package license
Summary: license components for the g2fs-utils package.
Group: Default

%description license
license components for the g2fs-utils package.


%package man
Summary: man components for the g2fs-utils package.
Group: Default

%description man
man components for the g2fs-utils package.


%prep
%setup -q -n gfs2-utils-3.2.0
cd %{_builddir}/gfs2-utils-3.2.0

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1582350345
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FCFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=4 "
%autogen --disable-static
make  %{?_smp_mflags}

%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make VERBOSE=1 V=1 %{?_smp_mflags} check

%install
export SOURCE_DATE_EPOCH=1582350345
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/g2fs-utils
cp %{_builddir}/gfs2-utils-3.2.0/doc/COPYING.applications %{buildroot}/usr/share/package-licenses/g2fs-utils/06877624ea5c77efe3b7e39b0f909eda6e25a4ec
cp %{_builddir}/gfs2-utils-3.2.0/doc/COPYING.libraries %{buildroot}/usr/share/package-licenses/g2fs-utils/9a1929f4700d2407c70b507b3b2aaf6226a9543c
cp %{_builddir}/gfs2-utils-3.2.0/doc/README.licence %{buildroot}/usr/share/package-licenses/g2fs-utils/d0858a94855bdbf10d6825b75b43d35d3184e275
%make_install

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/fsck.gfs2
/usr/bin/gfs2_convert
/usr/bin/gfs2_edit
/usr/bin/gfs2_grow
/usr/bin/gfs2_jadd
/usr/bin/gfs2_lockcapture
/usr/bin/gfs2_trace
/usr/bin/gfs2_withdraw_helper
/usr/bin/glocktop
/usr/bin/mkfs.gfs2
/usr/bin/tunegfs2

%files config
%defattr(-,root,root,-)
/usr/lib/udev/rules.d/82-gfs2-withdraw.rules

%files doc
%defattr(0644,root,root,0755)
/usr/share/doc/gfs2-utils/COPYING.applications
/usr/share/doc/gfs2-utils/COPYING.libraries
/usr/share/doc/gfs2-utils/COPYRIGHT
/usr/share/doc/gfs2-utils/README.contributing
/usr/share/doc/gfs2-utils/README.licence
/usr/share/doc/gfs2-utils/gfs2.txt
/usr/share/doc/gfs2-utils/journaling.txt

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/g2fs-utils/06877624ea5c77efe3b7e39b0f909eda6e25a4ec
/usr/share/package-licenses/g2fs-utils/9a1929f4700d2407c70b507b3b2aaf6226a9543c
/usr/share/package-licenses/g2fs-utils/d0858a94855bdbf10d6825b75b43d35d3184e275

%files man
%defattr(0644,root,root,0755)
/usr/share/man/man5/gfs2.5
/usr/share/man/man8/fsck.gfs2.8
/usr/share/man/man8/gfs2_convert.8
/usr/share/man/man8/gfs2_edit.8
/usr/share/man/man8/gfs2_grow.8
/usr/share/man/man8/gfs2_jadd.8
/usr/share/man/man8/gfs2_lockcapture.8
/usr/share/man/man8/gfs2_trace.8
/usr/share/man/man8/glocktop.8
/usr/share/man/man8/mkfs.gfs2.8
/usr/share/man/man8/tunegfs2.8
